apiVersion: v1
kind: Secret
metadata:
  name: slemicro
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -e
    secrets=$(dirname $0)
    transactional-update -n migration
    [ -f /run/reboot-needed ] && shutdown -r +1